name: preprocess
channels:
  - conda-forge
dependencies:
  - python=3.11.14
  - pip
  - numpy=1.26.4
  - scipy=1.16.3
  - pandas=2.3.3
  - pyyaml=6.0.3
  - joblib=1.4.2
  - scikit-learn=1.7.2
  - matplotlib=3.10.8
  - pyside6=6.9.2
  - spikeinterface=0.103.2
  - pytest=9.0.1
  - ipykernel=7.1.0
  - jupyterlab
  - marimo
  - pip:
      - -e .
